### ISSUE TITLE
No way to bind aggregate to variable in query

### ISSUE THREAD

**Issue by thomcc** [mozilla/mentat#815] opened 2018-08-23 01:04 UTC
The [datomic docs](https://docs.datomic.com/on-prem/query.html) have an example query of the form:

```edn
[:find ?year (median ?namelen) (avg ?namelen) (stddev ?namelen)
 :with ?track
 :where [?track :track/name ?name]
        [(count ?name) ?namelen]
        [?medium :medium/tracks ?track]
        [?release :release/media ?medium]
        [?release :release/year ?year]]
```

Our query syntax doesn't allow the `[(count ?name) ?namelen]` clause.

Between this and https://github.com/mozilla/mentat/issues/647 I'm not sure we can implement a top-sites like query directly. (That might not be true, and could just a reflection of my ignorance, though!)

**Comment by thomcc** [comment] 2018-08-23 01:06
Possibly a duplicate of #750?

**Comment by rnewman** [comment] 2018-08-23 02:31
Yep, dupe of that.

**Closed** 2018-08-23 02:31 UTC
Labels: A-query
